# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

version: '2'

services:
  zookeeper:
    image: hyperledger/fabric-zookeeper
    restart: always
    ports:
      - '2181'
      - '2888'
      - '3888'

  kafka:
    image: hyperledger/fabric-kafka
    restart: always
    environment:
      - KAFKA_MESSAGE_MAX_BYTES=103809024 # 99 * 1024 * 1024 B
      - KAFKA_REPLICA_FETCH_MAX_BYTES=103809024 # 99 * 1024 * 1024 B
      - KAFKA_UNCLEAN_LEADER_ELECTION_ENABLE=false
      # TLS kafka
      - KAFKA_SSL_ENABLED_PROTOCOLS=TLSv1.2,TLSv1.1,TLSv1
      - KAFKA_SSL_INTER_BROKER_PROTOCOL=SSL
    volumes:
      - ../kafka/ssl/server.keystore.jks:/var/private/ssl/kafka0.server.keystore.jks
      - ../kafka/ssl/server.truststore.jks:/var/private/ssl/kafka0.server.truststore.jks
      - ../kafka/ssl/server1.keystore.jks:/var/private/ssl/kafka1.server.keystore.jks
      - ../kafka/ssl/server1.truststore.jks:/var/private/ssl/kafka1.server.truststore.jks
      - ../kafka/ssl/server2.keystore.jks:/var/private/ssl/kafka2.server.keystore.jks
      - ../kafka/ssl/server2.truststore.jks:/var/private/ssl/kafka2.server.truststore.jks
      - ../kafka/ssl/server3.keystore.jks:/var/private/ssl/kafka3.server.keystore.jks
      - ../kafka/ssl/server3.truststore.jks:/var/private/ssl/kafka3.server.truststore.jks
      - ../kafka/ssl/server4.keystore.jks:/var/private/ssl/kafka4.server.keystore.jks
      - ../kafka/ssl/server4.truststore.jks:/var/private/ssl/kafka4.server.truststore.jks
      - ../kafka/ssl/server5.keystore.jks:/var/private/ssl/kafka5.server.keystore.jks
      - ../kafka/ssl/server5.truststore.jks:/var/private/ssl/kafka5.server.truststore.jks
      - ../kafka/ssl/server6.keystore.jks:/var/private/ssl/kafka6.server.keystore.jks
      - ../kafka/ssl/server6.truststore.jks:/var/private/ssl/kafka6.server.truststore.jks
      - ../kafka/ssl/server7.keystore.jks:/var/private/ssl/kafka7.server.keystore.jks
      - ../kafka/ssl/server7.truststore.jks:/var/private/ssl/kafka7.server.truststore.jks
      - ../kafka/ssl/server8.keystore.jks:/var/private/ssl/kafka8.server.keystore.jks
      - ../kafka/ssl/server8.truststore.jks:/var/private/ssl/kafka8.server.truststore.jks
      - ../kafka/ssl/server9.keystore.jks:/var/private/ssl/kafka9.server.keystore.jks
      - ../kafka/ssl/server9.truststore.jks:/var/private/ssl/kafka9.server.truststore.jks

    ports:
      - '9093'
      - '9092'

  orderer.example.com:
    container_name: orderer.example.com
    image: hyperledger/fabric-orderer${IMAGE_TAG_FABRIC}
    environment:
      - ORDERER_GENERAL_LOGLEVEL=debug
      - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0
      - ORDERER_GENERAL_GENESISMETHOD=file
      - ORDERER_GENERAL_GENESISFILE=/var/hyperledger/orderer/orderer.genesis.block
      - ORDERER_GENERAL_LOCALMSPID=OrdererMSP
      - ORDERER_GENERAL_LOCALMSPDIR=/var/hyperledger/orderer/msp
      # enabled TLS
      - ORDERER_GENERAL_TLS_ENABLED=true
      - ORDERER_GENERAL_TLS_PRIVATEKEY=/var/hyperledger/orderer/tls/server.key
      - ORDERER_GENERAL_TLS_CERTIFICATE=/var/hyperledger/orderer/tls/server.crt
      - ORDERER_GENERAL_TLS_ROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]
      # - ORDERER_GENERAL_TLS_CLIENTAUTHREQUIRED = true
      # - ORDERER_GENERAL_TLS_CLIENTROOTCAS = [/var/hyperledger/users/tls/ca.crt]
      # Kafka
      - ORDERER_KAFKA_RETRY_SHORTINTERVAL=1s
      - ORDERER_KAFKA_RETRY_SHORTTOTAL=30s
      - ORDERER_KAFKA_VERBOSE=true
      - ORDERER_KAFKA_BROKERS=[kafka0:9093, kafka1:9093, kafka2:9093, kafka3:9093, kafka4:9093, kafka5:9093, kafka6:9093, kafka7:9093, kafka8:9093, kafka9:9093]
       # enabled kafka client TLS
      - ORDERER_KAFKA_TLS_ENABLED=true
      - ORDERER_KAFKA_TLS_PRIVATEKEY_FILE=/var/private/ssl/client-key.pem
      - ORDERER_KAFKA_TLS_CERTIFICATE_FILE=/var/private/ssl/client-cert-signed.pem
      - ORDERER_KAFKA_TLS_ROOTCAS_FILE=/var/private/ssl/ca-cert.pem
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric
    command: orderer
    volumes:
    - ../channel-artifacts/genesis.block:/var/hyperledger/orderer/orderer.genesis.block
    - ../crypto-config/ordererOrganizations/example.com/orderers/orderer.example.com/msp:/var/hyperledger/orderer/msp
    - ../crypto-config/ordererOrganizations/example.com/orderers/orderer.example.com/tls/:/var/hyperledger/orderer/tls
    #- ../crypto-config/ordererOrganizations/example.com/users/Admin@example.com/tls/:/var/hyperledger/users/tls
    - ../kafka/ssl/ca-cert.pem:/var/private/ssl/ca-cert.pem
    - ../kafka/ssl/client-cert-signed.pem:/var/private/ssl/client-cert-signed.pem
    - ../kafka/ssl/client-key.pem:/var/private/ssl/client-key.pem
    ports:
      - 7050:7050

  peer0.org1.example.com:
    container_name: peer0.org1.example.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer0.org1.example.com
      - CORE_PEER_ADDRESS=peer0.org1.example.com:7051
      - CORE_PEER_CHAINCODEADDRESS=peer0.org1.example.com:7052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:7052
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.org1.example.com:7051
      - CORE_PEER_LOCALMSPID=Org1MSP
    volumes:
      - /var/run/:/host/var/run/
      - ../crypto-config/peerOrganizations/org1.example.com/peers/peer0.org1.example.com/msp:/etc/hyperledger/fabric/msp
      - ../crypto-config/peerOrganizations/org1.example.com/peers/peer0.org1.example.com/tls:/etc/hyperledger/fabric/tls
    ports:
      - 7051:7051
      - 7052:7052
      - 7053:7053

  peer1.org1.example.com:
    container_name: peer0.org1.example.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer1.org1.example.com
      - CORE_PEER_ADDRESS=peer1.org1.example.com:7051
      - CORE_PEER_CHAINCODEADDRESS=peer1.org1.example.com:7052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:7052
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.org1.example.com:7051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.org1.example.com:7051
      - CORE_PEER_LOCALMSPID=Org1MSP
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/org1.example.com/peers/peer1.org1.example.com/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/org1.example.com/peers/peer1.org1.example.com/tls:/etc/hyperledger/fabric/tls
    ports:
      - 9051:7051
      - 9052:7052
      - 9053:7053