# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

version: '2'

services:
  ca0:
    image: hyperledger/fabric-ca${IMAGE_TAG_FABRIC_CA}
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca-org1
      - FABRIC_CA_SERVER_DB_TYPE=postgres
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_TLS_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.org1.example.com-cert.pem
      - FABRIC_CA_SERVER_TLS_KEYFILE=/etc/hyperledger/fabric-ca-server-config/
    ports:
      - "7054:7054"
    command: sh -c 'fabric-ca-server start -n ca0 --cfg.identities.allowremove --cfg.affiliations.allowremove --registry.maxenrollments -1 --ca.certfile /etc/hyperledger/fabric-ca-server-config/ca.org1.example.com-cert.pem --ca.keyfile /etc/hyperledger/fabric-ca-server-config/*_sk -b admin:adminpw ${ORG_HYPERLEDGER_FABRIC_SDKTEST_INTEGRATIONTESTS_CA_TLS} --tls.certfile /etc/hyperledger/fabric-ca-server-config/ca.org1.example.com-cert.pem --tls.keyfile /etc/hyperledger/fabric-ca-server-config/*_sk -d'
    volumes:
      - ./ca-server/:/etc/hyperledger/fabric-ca-server
      - ./crypto-config/peerOrganizations/org1.example.com/ca/:/etc/hyperledger/fabric-ca-server-config
    container_name: ca_peerOrg1

  zookeeper0:
    container_name: zookeeper0
    extends:
      file: base/docker-compose-base2.yaml
      service: zookeeper
    environment:
      - ZOO_MY_ID=1
      - ZOO_SERVERS=server.1=zookeeper0:2888:3888 server.2=zookeeper1:2888:3888 server.3=zookeeper2:2888:3888


  zookeeper1:
    container_name: zookeeper1
    extends:
      file: base/docker-compose-base2.yaml
      service: zookeeper
    environment:
      - ZOO_MY_ID=2
      - ZOO_SERVERS=server.1=zookeeper0:2888:3888 server.2=zookeeper1:2888:3888 server.3=zookeeper2:2888:3888


  zookeeper2:
    container_name: zookeeper2
    extends:
      file: base/docker-compose-base2.yaml
      service: zookeeper
    environment:
      - ZOO_MY_ID=3
      - ZOO_SERVERS=server.1=zookeeper0:2888:3888 server.2=zookeeper1:2888:3888 server.3=zookeeper2:2888:3888


  kafka0:
    container_name: kafka0
    extends:
      file: base/docker-compose-base2.yaml
      service: kafka
    environment:
      - KAFKA_BROKER_ID=0
      - KAFKA_MIN_INSYNC_REPLICAS=2
      - KAFKA_DEFAULT_REPLICATION_FACTOR=3
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper0:2181,zookeeper1:2181,zookeeper2:2181
      - KAFKA_ADVERTISED_HOST_NAME=kafka0
      - KAFKA_SSL_KEYSTORE_LOCATION=/var/private/ssl/kafka0.server.keystore.jks
      - KAFKA_SSL_KEYSTORE_PASSWORD=test1234
      - KAFKA_SSL_KEY_PASSWORD=test1234
      - KAFKA_SSL_TRUSTSTORE_LOCATION=/var/private/ssl/kafka0.server.truststore.jks
      - KAFKA_SSL_TRUSTSTORE_PASSWORD=test1234
      - KAFKA_LISTENERS=PLAINTEXT://kafka0:9092,SSL://kafka0:9093
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka0:9092,SSL://kafka0:9093
      - ZOOKEEPER_CONNECTION_TIMEOUT_MS = 10000
      - ZOOKEEPER_SESSION_TIMEOUT_MS = 10000
    depends_on:
      - zookeeper0
      - zookeeper1
      - zookeeper2


  kafka1:
    container_name: kafka1
    extends:
      file: base/docker-compose-base2.yaml
      service: kafka
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_MIN_INSYNC_REPLICAS=2
      - KAFKA_DEFAULT_REPLICATION_FACTOR=3
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper0:2181,zookeeper1:2181,zookeeper2:2181
      - KAFKA_ADVERTISED_HOST_NAME=kafka1
      - KAFKA_SSL_KEYSTORE_LOCATION=/var/private/ssl/kafka1.server.keystore.jks
      - KAFKA_SSL_KEYSTORE_PASSWORD=test1234
      - KAFKA_SSL_KEY_PASSWORD=test1234
      - KAFKA_SSL_TRUSTSTORE_LOCATION=/var/private/ssl/kafka1.server.truststore.jks
      - KAFKA_SSL_TRUSTSTORE_PASSWORD=test1234
      - KAFKA_LISTENERS=PLAINTEXT://kafka1:9092,SSL://kafka1:9093
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka1:9092,SSL://kafka1:9093
      - ZOOKEEPER_CONNECTION_TIMEOUT_MS = 10000
      - ZOOKEEPER_SESSION_TIMEOUT_MS = 10000
    depends_on:
      - zookeeper0
      - zookeeper1
      - zookeeper2
  
  kafka2:
    container_name: kafka2
    extends:
      file: base/docker-compose-base2.yaml
      service: kafka
    environment:
      - KAFKA_BROKER_ID=2
      - KAFKA_MIN_INSYNC_REPLICAS=2
      - KAFKA_DEFAULT_REPLICATION_FACTOR=3
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper0:2181,zookeeper1:2181,zookeeper2:2181
      - KAFKA_ADVERTISED_HOST_NAME=kafka2
      - KAFKA_SSL_KEYSTORE_LOCATION=/var/private/ssl/kafka2.server.keystore.jks
      - KAFKA_SSL_KEYSTORE_PASSWORD=test1234
      - KAFKA_SSL_KEY_PASSWORD=test1234
      - KAFKA_SSL_TRUSTSTORE_LOCATION=/var/private/ssl/kafka2.server.truststore.jks
      - KAFKA_SSL_TRUSTSTORE_PASSWORD=test1234
      - KAFKA_LISTENERS=PLAINTEXT://kafka2:9092,SSL://kafka2:9093
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka2:9092,SSL://kafka2:9093
      - ZOOKEEPER_CONNECTION_TIMEOUT_MS = 10000
      - ZOOKEEPER_SESSION_TIMEOUT_MS = 10000
    depends_on:
      - zookeeper0
      - zookeeper1
      - zookeeper2
    

  kafka3:
    container_name: kafka3
    extends:
      file: base/docker-compose-base2.yaml
      service: kafka
    environment:
      - KAFKA_BROKER_ID=3
      - KAFKA_MIN_INSYNC_REPLICAS=2
      - KAFKA_DEFAULT_REPLICATION_FACTOR=3
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper0:2181,zookeeper1:2181,zookeeper2:2181
      - KAFKA_ADVERTISED_HOST_NAME=kafka3
      - KAFKA_SSL_KEYSTORE_LOCATION=/var/private/ssl/kafka3.server.keystore.jks
      - KAFKA_SSL_KEYSTORE_PASSWORD=test1234
      - KAFKA_SSL_KEY_PASSWORD=test1234
      - KAFKA_SSL_TRUSTSTORE_LOCATION=/var/private/ssl/kafka3.server.truststore.jks
      - KAFKA_SSL_TRUSTSTORE_PASSWORD=test1234
      - KAFKA_LISTENERS=PLAINTEXT://kafka3:9092,SSL://kafka3:9093
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka3:9092,SSL://kafka3:9093
      - ZOOKEEPER_CONNECTION_TIMEOUT_MS = 10000
      - ZOOKEEPER_SESSION_TIMEOUT_MS = 10000
    depends_on:
      - zookeeper0
      - zookeeper1
      - zookeeper2
   

  orderer.example.com:
    extends:
      file:   base/docker-compose-base2.yaml
      service: orderer.example.com
    container_name: orderer.example.com
    depends_on:
      - kafka0
      - kafka1
      - kafka2
      - kafka3

  orderer1.example.com:
    extends:
      file:   base/docker-compose-base2.yaml
      service: orderer1.example.com
    container_name: orderer1.example.com
    depends_on:
      - kafka0
      - kafka1
      - kafka2
      - kafka3

  peer0.org1.example.com:
    container_name: peer0.org1.example.com
    extends:
      file:  base/docker-compose-base2.yaml
      service: peer0.org1.example.com
    depends_on:
      - orderer.example.com
    

  peer1.org1.example.com:
    container_name: peer1.org1.example.com
    extends:
      file:  base/docker-compose-base2.yaml
      service: peer1.org1.example.com
    depends_on:
       - orderer.example.com
       - peer0.org1.example.com
  

  peer2.org1.example.com:
    container_name: peer2.org1.example.com
    extends:
      file:  base/docker-compose-base2.yaml
      service: peer2.org1.example.com
    depends_on:
       - orderer.example.com
       - peer0.org1.example.com

  peer3.org1.example.com:
    container_name: peer3.org1.example.com
    extends:
      file:  base/docker-compose-base2.yaml
      service: peer3.org1.example.com
    depends_on:
       - orderer.example.com
       - peer0.org1.example.com
    

  peer4.org1.example.com:
    container_name: peer4.org1.example.com
    extends:
      file:  base/docker-compose-base2.yaml
      service: peer4.org1.example.com
    depends_on:
      - orderer.example.com
      - peer0.org1.example.com

  peer5.org1.example.com:
    container_name: peer5.org1.example.com
    extends:
      file:  base/docker-compose-base2.yaml
      service: peer5.org1.example.com
    depends_on:
       - orderer.example.com
       - peer0.org1.example.com
  
  peer6.org1.example.com:
    container_name: peer6.org1.example.com
    extends:
      file:  base/docker-compose-base2.yaml
      service: peer6.org1.example.com
    depends_on:
       - orderer.example.com
       - peer0.org1.example.com
  
  peer7.org1.example.com:
    container_name: peer7.org1.example.com
    extends:
      file:  base/docker-compose-base2.yaml
      service: peer7.org1.example.com
    depends_on:
       - orderer.example.com
       - peer0.org1.example.com

  configtxlator:
    image: hyperledger/fabric-tools${IMAGE_TAG_FABRIC}
    container_name: configtxlator
    ports:
      - "7059:7059"
    command: /usr/local/bin/configtxlator start

  ccenv:
    image: hyperledger/fabric-ccenv${IMAGE_TAG_FABRIC}
